default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: heroku_e0f2647cd289f11
  username: bd3db0e115de15
  password: 68d6b7ea
  host: us-cdbr-east-03.cleardb.com

production:
  <<: *default
  database: heroku_0481a74ef6f38a7
